import type { VoidComponent } from "solid-js";
import { Head, Title, Meta, Link } from "solid-start";
import Header from "~/components/header";

const About: VoidComponent = () => {
	return (
		<>
			<Head>
				<Title>Create Solid + tRPC</Title>
				<Meta name="description" content="Generated by create-jd-app" />
				<Link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<main class="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#026d56] to-[#152a2c] pt-[50px]">
				<div class="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
					<h1 class="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem] text-center">
						About Page
					</h1>
				</div>
			</main>
		</>
	);
};

export default About;
