import { type VoidComponent } from "solid-js";
import { Head, Title, Meta, Link } from "solid-start";
import { trpc } from "../utils/trpc";

const Home: VoidComponent = () => {
	const hello = trpc.example.hello.useQuery(() => ({ name: "from tRPC" }));

	return (
		<>
			<Head>
				<Title>Create JD App</Title>
				<Meta name="description" content="Generated by create-jd-app" />
				<Link rel="icon" href="/favicon.ico" />
			</Head>
			<main class="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#026d56] to-[#152a2c]">
				<div class="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
					<h1 class="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
						{hello.data ?? "Loading tRPC query"}
					</h1>
				</div>
			</main>
		</>
	);
};

export default Home;
