import type { Component, JSXElement } from "solid-js";
import { Head, Title, Meta, Link } from "solid-start";
import Header from "~/components/header";

const Wrapper: Component<{ children: JSXElement }> = (props) => {
	return (
		<>
			<Head>
				<Title>Create Solid + tRPC</Title>
				<Meta name="description" content="Generated by solid-template" />
				<Link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<main class="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#026d56] to-[#152a2c] pt-[50px]">
				{props.children}
			</main>
		</>
	);
};

export default Wrapper;
